version: '3.8'

services:
  kafka:
    # Bitnami의 Kafka 4.0 이미지 (KRaft 모드 지원)
    image: bitnami/kafka:4.0.0
    container_name: kafka_kraft
    environment:
      # 비암호화(PLAINTEXT) 리스너 사용 허용
      - ALLOW_PLAINTEXT_LISTENER=yes

      # 1) KRaft 모드 활성화: broker + controller
      - KAFKA_CFG_PROCESS_ROLES=broker,controller

      # 2) 브로커 겸 컨트롤러 노드 ID
      - KAFKA_CFG_NODE_ID=1

      # 3) 컨트롤러 쿼럼(voter) 설정 (단일 노드므로 1@서비스명:PORT)
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      # 4) 클라이언트/컨트롤러용 리스너
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      # 5) 외부(호스트)에서 접속할 주소
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.16.24.72:9092

      # 6) 컨트롤러 통신 리스너 이름
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # 7) 리스너별 보안 프로토콜 매핑
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

    ports:
      - '9092:9092'   # Producer/Consumer 접속 포트
      - '9093:9093'   # 내부 Controller 통신 포트

    # 데이터를 로컬 볼륨에 저장 (프로젝트별 격리)
    volumes:
      - ./kafka-data:/bitnami/kafka/data

    # 처음 실행 시 스토리지 포맷(UUD 주입 등)은
    # bitnami/kafka entrypoint가 자동으로 처리해 줍니다.