apiVersion: 1
datasources:
  - name: InfluxDB-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: k6
    secureJsonData:
      password: k6pass
    isDefault: false
    editable: true



